# Recommendations
## Introduction

Based on analysis of 25+ years of violence against aid workers, this section outlines key points and recommendations for key stakeholders in how to prevent further incidents and enhance aid worker safety.

## Strengthen Aid Worker Protection 
- **Invest in Local Staff Safety:**
  -  With the  majority of aid workers killed being nationals (accounting for 97% of aid worker deaths), agencies must learn to take protective measures for local staff.
- **Better Preperation:**
 - By implementing training programs to mitigate crises, while also employing security measures for high risk regions such as Gaza or South Sudan, local aid workers can be better equipped to respond to emergencies while also reducing their exposure to violence.


## Improve Real-Time Risk Monitoring
- **Identify Emerging Threats Quickly:**
  - Data shows that violence against aid workers spike suddenly, with many agencies not expecting and prepared
- **Implement Early Warning Systems:**
  - Using satellite data, or sharing intel amongst different agencies can help mitigate risk and prepare agencies for sudden attacks or incidents. 


## Impliment Legal Protection
- **Enforce Accountability:**
  - Start Holding perpetrators accountable through the enforcement of international humanitarian law.
- **Close the Justice Gap:**
  - Currently, despite Aid workers being protected under international, many incidents go unpunished.
- **Identify Repeat Offenders:**
  - In many cases, the same groups are responsible for the majority of incidents, such as in Palestine, the majority of deaths starting in 2023 were from aerial bombardments, often by state and foreign forces, while in South Sudan, non-state subnational groups are the main perpetrators since 2021, with no clear accountability.
  
## Adapting Operations 
- In regions that are under severe conflict or blockade, exploring safer options of delivering aid such as drone delivery or telehealth. 

## Prioritize High-Risk Zones
- Allocate resources and security based on data-driven hotspots and high-risk areas, such as:  
  - **Kabul, Afghanistan**  
    - Terrorism and insurgency

  - **Gaza, Palestine**  
    - Military occupation and airstrikes

  - **Juba & Rubkona, South Sudan**  
    - Civil unrest and subnational violence

## Supporting Local Communities 
- **Build Trust on the Ground:**
  - Engaging with local leaders and communities will lead to shared trust, and can prevent further attacks while making communities safer for all parties involved.
- **Strengthen Local Coordination:**
  - In Afghanistan, shootings and ambushes are  often targeted at  national aid convoys, suggesting that the lack of local trust and coordination can increase risk.
- **Address Root Causes of Violence:**
  - In South Sudan, violence by subnational non-state groups surged post-2021. These groups often emerge from local tensions and issues, indicating a need for local community engagement and support.

## Raise Global Awareness
- With violence against aid workers rising, especially since 2022, raising global awareness is essential.
- Clear data visualizations and storytelling can highlight overlooked hotspots, such as South Sudan, inform donors and policymakers, and encourage stronger protections through public pressure and policy change.





